In [1]:
import torch

print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

True
Tesla T4

In [4]:
import pandas as pd

df = pd.read_csv("../data/kaggle_raw/customer_support_tickets.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '../data/kaggle_raw/customer_support_tickets.csv'

In [9]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
import os

path = "/content/drive/MyDrive/SupportOpsAI/data/kaggle_raw/customer_support_tickets.csv"

print(os.path.exists(path))

True

In [13]:
import pandas as pd

df = pd.read_csv(path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Shape: (8469, 17)

Columns:
['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [14]:
print("Ticket Types:")
print(df["Ticket Type"].value_counts())

print("\nPriorities:")
print(df["Ticket Priority"].value_counts())

print("\nStatuses:")
print(df["Ticket Status"].value_counts())

Ticket Types:
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

Priorities:
Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

Statuses:
Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

In [ ]:
print(
    df[[
        "Ticket Type",
        "Ticket Subject",
        "Ticket Description",
        "Ticket Priority",
        "Resolution"
    ]].head(10)
)

            Ticket Type            Ticket Subject  \
0       Technical issue             Product setup
1       Technical issue  Peripheral compatibility
2       Technical issue           Network problem
3       Billing inquiry            Account access
4       Billing inquiry                 Data loss
5  Cancellation request             Payment issue
6       Product inquiry            Refund request
7        Refund request              Battery life
8       Technical issue      Installation support
9        Refund request             Payment issue

                                  Ticket Description Ticket Priority  \
0  I'm having an issue with the {product_purchase...        Critical
1  I'm having an issue with the {product_purchase...        Critical
2  I'm facing a problem with my {product_purchase...             Low
3  I'm having an issue with the {product_purchase...             Low
4  I'm having an issue with the {product_purchase...             Low
5  I'm facing a problem with my {product_purchase...             Low
6  I'm unable to access my {product_purchased} ac...        Critical
7  I'm having an issue with the {product_purchase...        Critical
8  I'm having an issue with the {product_purchase...             Low
9  My {product_purchased} is making strange noise...        Critical

                                      Resolution
0                                            NaN
1                                            NaN
2   Case maybe show recently my computer follow.
3  Try capital clearly never color toward story.
4                    West decision evidence bit.
5                                            NaN
6                                            NaN
7                                            NaN
8                                            NaN
9                                            NaN

In [18]:
for i, row in df.head(10).iterrows():
    print("=" * 80)
    print("TYPE:", row["Ticket Type"])
    print("SUBJECT:", row["Ticket Subject"])
    print("PRIORITY:", row["Ticket Priority"])
    print("DESCRIPTION:", row["Ticket Description"])

================================================================================
TYPE: Technical issue
SUBJECT: Product setup
PRIORITY: Critical
DESCRIPTION: I'm having an issue with the {product_purchased}. Please assist.

Your billing zip code is: 71701.

We appreciate that you have requested a website address.

Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.
================================================================================
TYPE: Technical issue
SUBJECT: Peripheral compatibility
PRIORITY: Critical
DESCRIPTION: I'm having an issue with the {product_purchased}. Please assist.

If you need to change an existing product.

I'm having an issue with the {product_purchased}. Please assist.

If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
================================================================================
TYPE: Technical issue
SUBJECT: Network problem
PRIORITY: Low
DESCRIPTION: I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.

1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.
================================================================================
TYPE: Billing inquiry
SUBJECT: Account access
PRIORITY: Low
DESCRIPTION: I'm having an issue with the {product_purchased}. Please assist.

If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.
================================================================================
TYPE: Billing inquiry
SUBJECT: Data loss
PRIORITY: Low
DESCRIPTION: I'm having an issue with the {product_purchased}. Please assist.


Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.
================================================================================
TYPE: Cancellation request
SUBJECT: Payment issue
PRIORITY: Low
DESCRIPTION: I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new {product_purch I've checked for any available software updates for my {product_purchased}, but there are none.
================================================================================
TYPE: Product inquiry
SUBJECT: Refund request
PRIORITY: Critical
DESCRIPTION: I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?

Solution 1 I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?
================================================================================
TYPE: Refund request
SUBJECT: Battery life
PRIORITY: Critical
DESCRIPTION: I'm having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.

Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.
================================================================================
TYPE: Technical issue
SUBJECT: Installation support
PRIORITY: Low
DESCRIPTION: I'm having an issue with the {product_purchased}. Please assist. Thank you.

{product_purchased} is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?
================================================================================
TYPE: Refund request
SUBJECT: Payment issue
PRIORITY: Critical
DESCRIPTION: My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?

} If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

In [19]:
print(
    df["Ticket Description"]
    .str.contains(r"\{.*?\}", regex=True, na=False)
    .sum(),
    "tickets contain placeholders"
)

8469 tickets contain placeholders

In [20]:
print(
    df["Resolution"].notna().sum(),
    "tickets have a resolution"
)

2769 tickets have a resolution

In [21]:
ls

drive/  sample_data/

In [23]:
ls

bin@                kaggle/                   proc/                sys/
bin.usr-is-merged/  lib@                      python-apt/          tmp/
boot/               lib64@                    python-apt.tar.xz*   tools/
content/            lib.usr-is-merged/        root/                usr/
datalab/            media/                    run/                 var/
dev/                mnt/                      sbin@
etc/                NGC-DL-CONTAINER-LICENSE  sbin.usr-is-merged/
home/               opt/                      srv/

In [24]:
!ls /content/drive/MyDrive/SupportOpsAI

data

In [25]:
!ls /content/drive/MyDrive/SupportOpsAI/data/kaggle_raw

customer_support_tickets.csv

In [27]:
import json
import random

text_col = "Ticket Description"

texts = df[text_col].dropna().astype(str).tolist()

random.seed(42)

sample = random.sample(
    texts,
    min(70, len(texts))
)

seed_path = "/content/drive/MyDrive/SupportOpsAI/data/seed_texts.jsonl"

with open(seed_path, "w", encoding="utf-8") as f:
    for t in sample:
        f.write(
            json.dumps(
                {"raw_text": t.strip()},
                ensure_ascii=False
            ) + "\n"
        )

print(f"Extracted {len(sample)} ticket texts")
print(f"Saved to: {seed_path}")

Extracted 70 ticket texts
Saved to: /content/drive/MyDrive/SupportOpsAI/data/seed_texts.jsonl

In [28]:
for i, ticket in enumerate(sample[:10], 1):
    print(f"\n--- Ticket {i} ---")
    print(ticket)

--- Ticket 1 ---
I'm having an issue with the {product_purchased}. Please assist. Thanks.

If you need a product for free, please use our support page. Please contact support@vendorsparklabs.com. I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 2 ---
My {product_purchased} crashed, and I lost all the data stored on it. Is there any way to recover the lost data? If your data is not safe from other users, I'd like to know how you managed to recover I've noticed that the issue occurs consistently when I use a specific feature or application on my {product_purchased}.

--- Ticket 3 ---
I've noticed a software bug in the {product_purchased} app. It's causing data loss and unexpected errors. How can I resolve this issue?

Install the Software

Open your Mac Settings > Applications > Privacy > Software I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.

--- Ticket 4 ---
I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.

This is a pain in the ass I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 5 ---
I'm having an issue with the {product_purchased}. Please assist.

"

"I feel like you're very responsible to me for knowing this product. I've been going through this since January 10th. Please assist I've tried different settings and configurations on my {product_purchased}, but the issue persists.

--- Ticket 6 ---
The {product_purchased} is unable to establish a stable internet connection. It keeps disconnecting intermittently. How can I troubleshoot this network problem? *

Note that the same thing can happen to your web apps when you I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?

--- Ticket 7 ---
I'm having an issue with the {product_purchased}. Please assist.

Your name?

If you are registering for the product, your product is now being purchased. The only difference, of course, is that your customer I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 8 ---
I'm having an issue with the {product_purchased}. Please assist. You can call or write us at 1-888-873-1060 to request information about ordering for a new product or have it removed.

We I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Ticket 9 ---
I'm having an issue with the {product_purchased}. Please assist. {{product_purchased}}

{product_refresh_to}} {{review_created}}

{review_total_refresh}} I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 10 ---
I'm having an issue with the {product_purchased}. Please assist. If you have any further feedback, please drop me an email at xanj@comcast.net.

[This post has been updated.] I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

In [29]:
for i, ticket in enumerate(sample[10:], 11):
    print(f"\n--- Ticket {i} ---")
    print(ticket)

--- Ticket 11 ---
I'm having an issue with the {product_purchased}. Please assist.

For a list of specific devices, please contact us.


If your product is not listed in the list on this page, please see our Help Center I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 12 ---
I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?

When the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

--- Ticket 13 ---
I'm having an issue with the {product_purchased}. Please assist. $55.00

1. Add # of items to cart

Add $55 (plus taxes) to cart.

Add Item to Cart I've checked the device settings and made sure that everything is configured correctly.

--- Ticket 14 ---
I'm having an issue with the {product_purchased}. Please assist.


Dangerous and difficult to remove or discard:


Lethally-based products do NOT have to be discarded. It is important to avoid putting I've checked for software updates, and my {product_purchased} is already running the latest version.

--- Ticket 15 ---
I'm having an issue with the {product_purchased}. Please assist. I'll fix it as quickly as I can! Thank you."

It's not just the text that changes these numbers that makes the results appear to be wrong I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Ticket 16 ---
I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account? The account is temporarily I've tried using different cables, adapters, or peripherals with my {product_purchased}, but the issue persists.

--- Ticket 17 ---
I've forgotten my password for my {product_purchased} account, and the password reset option is not working. How can I recover my account? 1. Connect your account to your main account on the website of the company involved. 2 I've checked for software updates, and my {product_purchased} is already running the latest version.

--- Ticket 18 ---
My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?

Hello dear reader here, this is the question I've wanted to ask I need assistance as soon as possible because it's affecting my work and productivity.

--- Ticket 19 ---
I'm having an issue with the {product_purchased}. Please assist. Thank You.

My Santa gave me 2 great gifts including a very nice gift card which has a "Buck I Don't Know"-shaped hat I've I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket 20 ---
I'm having an issue with the {product_purchased}. Please assist.

This button opens a dialog that displays additional images for this product with the option to zoom in or out.

Please note that some brands ship with custom I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 21 ---
I'm having an issue with the {product_purchased}. Please assist. If you have any problems please report an issue now, and we will fix them asap.


And please join in by joining my mailing list. I've checked for software updates, and my {product_purchased} is already running the latest version.

--- Ticket 22 ---
I'm having an issue with the {product_purchased}. Please assist. I've checked the device settings and made sure that everything is configured correctly.

--- Ticket 23 ---
I'm having an issue with the {product_purchased}. Please assist. I've noticed that the issue occurs consistently when I use a specific feature or application on my {product_purchased}.

--- Ticket 24 ---
I'm having an issue with the {product_purchased}. Please assist.

* This item has an "error description" on its description page in some languages*

C-Y "I'm seeing a product now sold by I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 25 ---
I'm having an issue with the {product_purchased}. Please assist. Thanks. It will be fine.

(4) The product is for your personal use only. It does not constitute a license to use the other product. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 26 ---
I've accidentally deleted important data from my {product_purchased}. Is there any way to recover the deleted files? I need them urgently. When I use {name}{name_purchased}, the {products} information, I know I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 27 ---
I'm having an issue with the {product_purchased}. Please assist. A copy of my refund request can usually be found at the link below. Please note that while I'm very happy to assist you with any items that may possibly be I need assistance as soon as possible because it's affecting my work and productivity.

--- Ticket 28 ---
There seems to be a glitch in the {product_purchased} software. It freezes frequently, making it difficult to use. Can you please provide a solution?

There seems to be a glitch in the {product_purchased I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 29 ---
I've noticed a software bug in the {product_purchased} app. It's causing data loss and unexpected errors. How can I resolve this issue?

Here's what you CAN do:

Search for your project's { I'm worried that the issue might be hardware-related and might require repair or replacement.

--- Ticket 30 ---
I'm having an issue with the {product_purchased}. Please assist.

C# C++

C# 6

<-bool fDebug = "Error reporting to {product_purchased}.

" I've tried different settings and configurations on my {product_purchased}, but the issue persists.

--- Ticket 31 ---
I'm facing issues logging into my {product_purchased} account. It says my account is locked. What should I do to unlock it?

What is the solutionestead.pl?

This was written by Daniel S. I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.

--- Ticket 32 ---
I'm having an issue with the {product_purchased}. Please assist.

It seems that there's a bug in this API, so you'll want to enable the 'allow'option to use the URL you want to display when I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.

--- Ticket 33 ---
I'm encountering a software bug in the {product_purchased}. Whenever I try to perform a specific action, the application crashes. Are there any updates or fixes available? What should I do if the code crashes? Why? If I use I need assistance as soon as possible because it's affecting my work and productivity.

--- Ticket 34 ---
I've noticed a software bug in the {product_purchased} app. It's causing data loss and unexpected errors. How can I resolve this issue?

This issue affects all Android apps, not just yours. If you're on I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?

--- Ticket 35 ---
I'm having an issue with the {product_purchased}. Please assist. I have an issue with the {product_purchased}. Please assist.


This item is marked with a check mark. Please enter a valid email address I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket 36 ---
I'm having an issue with the {product_purchased}. Please assist. </td> <td align='center' class='western' display='stdText'></td> <td align='center' class='western' display=' I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?

--- Ticket 37 ---
I'm having an issue with the {product_purchased}. Please assist. Thank you if you'll be a quick touch to help you find what you are looking for. I've checked for any available software updates for my {product_purchased}, but there are none.

--- Ticket 38 ---
My {product_purchased} crashed, and I lost all the data stored on it. Is there any way to recover the lost data?

CMS_T Skydragon_DATA=0x4

CMS_TRUE I need assistance as soon as possible because it's affecting my work and productivity.

--- Ticket 39 ---
I'm having an issue with the {product_purchased}. Please assist. Please contact me. Thank you for the opportunity to purchase your product.. If I purchase with my own funds, I will ship to you for my product (including any I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?

--- Ticket 40 ---
I'm having an issue with the {product_purchased}. Please assist.

It's the only way to receive an address that goes directly to the product you've placed, but even if it's in the same brand, I can I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Ticket 41 ---
I'm having an issue with the {product_purchased}. Please assist. Thank you.

The product_purchased contains all our products and our services are the exclusive property of our supplier, our distributors, and our respective affiliates I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.

--- Ticket 42 ---
I'm having an issue with the {product_purchased}. Please assist.

This product is now out of stock and will get replaced.

This product is now out of stock and will get replaced.

This product is I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 43 ---
I'm having an issue with the {product_purchased}. Please assist.

To make your account secure, please use a secure browser, you may download additional images from this page, or if the client already supports JavaScript enabled, enable I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Ticket 44 ---
I'm having an issue with the {product_purchased}. Please assist. Thank you. I've been told that the product you provided is not a valid e-mail to the recipient. The e-mail can be reviewed by the appropriate I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.

--- Ticket 45 ---
I'm having an issue with the {product_purchased}. Please assist.


This does not mean you are having any issues, we merely want a speedy fix as soon as possible. I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?

--- Ticket 46 ---
I'm having an issue with the {product_purchased}. Please assist.

Your purchase will be valid only if this item is in retail and shipped.

*Product_sizes are for retail only.

Your purchase I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 47 ---
I'm having an issue with the {product_purchased}. Please assist. $14 to $14 US

PURCHASE AVAILABLE NOW at www.champagewide.com

Lorem Ipsum I've tried using different cables, adapters, or peripherals with my {product_purchased}, but the issue persists.

--- Ticket 48 ---
My {product_purchased} crashed, and I lost all the data stored on it. Is there any way to recover the lost data? This will be the end of my account and I won't have any credit cards that need to be I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 49 ---
I've encountered a data loss issue with my {product_purchased}. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? Thanks!

What was wrong with my data?

" I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Ticket 50 ---
I'm having an issue with the {product_purchased}. Please assist.

$29.50 $29.00 $29.00 Quantity

Pressed In 2 oz - $29.50

Pressed In 2 I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.

--- Ticket 51 ---
There seems to be a hardware problem with my {product_purchased}. The screen is flickering, and I'm unable to use it. What should I do?

- If you use this on a non-smart phone like the Galaxy I need assistance as soon as possible because it's affecting my work and productivity.

--- Ticket 52 ---
I'm having an issue with the {product_purchased}. Please assist.

14 14:25:08 noop, b0j, q1f9:3f, g, 6a:5b5, f I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.

--- Ticket 53 ---
I'm having an issue with the {product_purchased}. Please assist. https://support.apple.com/kb/HT312911

8 annotation : The author of the book may be notified and the details of any disputes I've checked for software updates, and my {product_purchased} is already running the latest version.

--- Ticket 54 ---
My {product_purchased} crashed, and I lost all the data stored on it. Is there any way to recover the lost data? I had been in some trouble as a user, and I needed a password to access all of the I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 55 ---
I'm having an issue with the {product_purchased}. Please assist.

1. Please click on the "Product Purchase" link in the Shopping Cart on the right.

2. If an issue persists after signing up, The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket 56 ---
I'm having an issue with the {product_purchased}. Please assist.

Thanks

Brianna D.

Founder, RVA Systems, Inc

Senior Designer

Caitlin

Senior Designer I've checked the device settings and made sure that everything is configured correctly.

--- Ticket 57 ---
I'm having an issue with the {product_purchased}. Please assist. I'm sorry if that might be a bad idea, but I'd rather not have it.

Sierra: Thank you so much for your time and help I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?

--- Ticket 58 ---
I'm having an issue with the {product_purchased}. Please assist. 1:14pm CDT by Akshay Mistry from New York - Akshay Mistry (aka Akshay) The book is about the life I've checked for software updates, and my {product_purchased} is already running the latest version.

--- Ticket 59 ---
I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.


What is the solution at the moment I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 60 ---
I'm having an issue with the {product_purchased}. Please assist. You will need:

a package with an id that must appear at the start of the URL

an ID of the product that you wanted to obtain I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?

--- Ticket 61 ---
I'm having an issue with the {product_purchased}. Please assist.

{product_purchased}.add to ProductID, ( ProductId = ProductID ).isValid, ( itemId = ProductId ) I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 62 ---
I'm having an issue with the {product_purchased}. Please assist. I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.

--- Ticket 63 ---
I'm having an issue with the {product_purchased}. Please assist.

Thanks! I've tried using different cables, adapters, or peripherals with my {product_purchased}, but the issue persists.

--- Ticket 64 ---
I'm having an issue with the {product_purchased}. Please assist.

The items can not be backordered due to how they were received.

You will receive tracking information when you first log on to this site. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket 65 ---
There seems to be a hardware problem with my {product_purchased}. The screen is flickering, and I'm unable to use it. What should I do?

What about any other devices that have a broken resolution?

What The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket 66 ---
I've accidentally deleted important data from my {product_purchased}. Is there any way to recover the deleted files? I need them urgently. Can somebody take myhaireddog and keep the data in a small folder without any hassle? I've checked for any available software updates for my {product_purchased}, but there are none.

--- Ticket 67 ---
I'm having an issue with the {product_purchased}. Please assist. Please help us in solving this problem. This is why we need your help. Contact us soon.

Our Customer Service

The Products and Services Customer Service I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?

--- Ticket 68 ---
I'm having an issue with the {product_purchased}. Please assist.

The product name is'mall', which means for example 'Plum' or 'Felise', if the product has been 'paid for' The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket 69 ---
The {product_purchased} is unable to establish a stable internet connection. It keeps disconnecting intermittently. How can I troubleshoot this network problem?

Try:

$ docker run -d # Create a Dockerfile I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Ticket 70 ---
I'm having an issue with the {product_purchased}. Please assist. If the product is not already stocked, I may need to charge another retail price. Your order will be shipped as soon as the items are sorted. I apologize for I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.

In [30]:
import pandas as pd

path = "/content/drive/MyDrive/SupportOpsAI/data/kaggle_raw/ticket_helpdesk_labeled_multi_languages_english_spain_french_german.csv"

df = pd.read_csv(path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (200, 8)

Columns:
['queue', 'priority', 'software_used', 'hardware_used', 'accounting_category', 'language', 'subject', 'text']

In [31]:
df.head()

,queue,priority,software_used,hardware_used,accounting_category,language,subject,text
0,Hardware,2,NaN,Wireless Mouse,NaN,en,Wireless Mouse suddenly stops working,"Dear Support Team, I've been using the Wireles..."
1,Hardware,2,NaN,IP PBX,NaN,fr,Problème de connexions IP PBX,"Bonjour, nous rencontrons un problème avec not..."
2,Hardware,2,NaN,SFX-Netzteil,NaN,de,Problem mit meinem SFX-Netzteil,"Sehr geehrte Damen und Herren, mein SFX-Netzte..."
3,Accounting,2,NaN,NaN,Customer Inquiries::Technical Support,en,Invoice Adjustment Request,"Dear Customer Support,\nI recently received my..."
4,Software,2,Arbitrum,NaN,NaN,en,Issue with Arbitrum: UI not loading,"Hello Support Team,\nI've been experiencing an..."

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   queue                200 non-null    object
 1   priority             200 non-null    int64
 2   software_used        83 non-null     object
 3   hardware_used        66 non-null     object
 4   accounting_category  51 non-null     object
 5   language             200 non-null    object
 6   subject              200 non-null    object
 7   text                 200 non-null    object
dtypes: int64(1), object(7)
memory usage: 12.6+ KB

In [33]:
english_df = df[df["language"] == "en"].copy()

print("English tickets:", len(english_df))
print("\nQueues:")
print(english_df["queue"].value_counts())

print("\nPriorities:")
print(english_df["priority"].value_counts())

English tickets: 78

Queues:
queue
Hardware      33
Software      23
Accounting    22
Name: count, dtype: int64

Priorities:
priority
3    32
2    29
1    17
Name: count, dtype: int64

In [34]:
english_df[["queue", "priority", "subject", "text"]].head(10)

,queue,priority,subject,text
0,Hardware,2,Wireless Mouse suddenly stops working,"Dear Support Team, I've been using the Wireles..."
3,Accounting,2,Invoice Adjustment Request,"Dear Customer Support,\nI recently received my..."
4,Software,2,Issue with Arbitrum: UI not loading,"Hello Support Team,\nI've been experiencing an..."
9,Hardware,2,Issue with Portable Console - Screen flickering,The screen flickers randomly during use.
10,Hardware,2,Issue with NAS enclosure temperature,"Hello Support, my NAS enclosure is overheating..."
11,Accounting,2,Invoice Query: Changing Corporate Billing Details,"Dear Support Team,\nI am writing to request a ..."
13,Accounting,3,Issue with expense report submission,"Dear Accounting Team, I am having trouble subm..."
18,Accounting,2,Timesheet entry software malfunctioning,"Hello support team, our employees can't access..."
19,Hardware,3,Critical: Smart Pet Camera Complete Failure,"Hello Support,\nMy Smart Pet Camera suddenly s..."
20,Hardware,3,URGENT: USB-HUB malfunctioning - Need Assistan...,"Dear Support Team,My new USB-Hub, Model Q35-T,..."

In [37]:
from datasets import load_dataset

hf_dataset = load_dataset(
    "Tobi-Bueck/customer-support-tickets",
    split="train"
)

print(hf_dataset)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/7.75k [00:00<?, ?B/s]

aa_dataset-tickets-multi-lang-5-2-50-ver(…): reconstructing file:   0%|          |  0.00B / 26.0MB

aa_dataset-tickets-multi-lang-5-2-50-ver(…): downloading bytes:           |  0.00B

(…)set-tickets-german_normalized_50_5_2.csv:   0%|          | 0.00/8.33M [00:00<?, ?B/s]

dataset-tickets-multi-lang-4-20k.csv: reconstructing file:   0%|          |  0.00B / 18.8MB

dataset-tickets-multi-lang-4-20k.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/61765 [00:00<?, ? examples/s]

Dataset({
    features: ['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language', 'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8'],
    num_rows: 61765
})

In [38]:
print(hf_dataset.column_names)
print(hf_dataset[0])

['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language', 'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8']
{'subject': 'Wesentlicher Sicherheitsvorfall', 'body': 'Sehr geehrtes Support-Team,\\n\\nich möchte einen gravierenden Sicherheitsvorfall melden, der gegenwärtig mehrere Komponenten unserer Infrastruktur betrifft. Betroffene Geräte umfassen Projektoren, Bildschirme und Speicherlösungen auf Cloud-Plattformen. Der Grund für die Annahme ist, dass der Vorfall eine potenzielle Datenverletzung im Zusammenhang mit einer Cyberattacke darstellt, was ein erhebliches Risiko für sensible Informationen und den laufenden Geschäftsbetrieb unserer Organisation bedeutet.\\n\\nUnsere initialen Untersuchungen haben ungewöhnliche Aktivitäten und Abweichungen bei den Geräten ergeben. Trotz der Umsetzung unserer standardisierten Behebungs- und Eindämmungsmaßnahmen konnte die Bedrohung bislang nicht vollständig eliminiert.', 'answer': 'Vielen Dank für die Meldung des kritischen Sicherheitsvorfalls und die Bereitstellung der Übersicht über die betroffenen Geräte sowie der ergriffenen ersten Maßnahmen. Wir erkennen die Dringlichkeit und Schwere der Lage an und setzen alles daran, den Fall prioritär zu bearbeiten. Für eine umgehende Untersuchung benötigen wir zusätzliche Informationen: Bitte senden Sie uns spezifische Protokolle der betroffenen Projektoren, Bildschirme und Cloud-Speichersysteme, inklusive Zeitstempel verdächtiger Aktivitäten sowie ungewöhnlicher Fehlermeldungen. Falls möglich, fügen Sie auch eine Zusammenfassung der bereits durchgeführten Maßnahmen bei.', 'type': 'Incident', 'queue': 'Technical Support', 'priority': 'high', 'language': 'de', 'version': 51, 'tag_1': 'Security', 'tag_2': 'Outage', 'tag_3': 'Disruption', 'tag_4': 'Data Breach', 'tag_5': None, 'tag_6': None, 'tag_7': None, 'tag_8': None}

In [ ]:
import pandas as pd

tickets_df = hf_dataset.to_pandas()

print(tickets_df.shape)
tickets_df.head()

(61765, 16)

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51.0,Security,Outage,Disruption,Data Breach,None,None,None,None
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51.0,Account,Disruption,Outage,IT,Tech Support,None,None,None
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51.0,Product,Feature,Tech Support,None,None,None,None,None
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51.0,Billing,Payment,Account,Documentation,Feedback,None,None,None
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51.0,Product,Feature,Feedback,Tech Support,None,None,None,None

In [40]:
print("Languages:")
print(tickets_df["language"].value_counts())

print("\nQueues:")
print(tickets_df["queue"].value_counts())

print("\nPriorities:")
print(tickets_df["priority"].value_counts())

print("\nTypes:")
print(tickets_df["type"].value_counts())

Languages:
language
de    33504
en    28261
Name: count, dtype: int64

Queues:
queue
Technical Support                         14186
Product Support                            8960
Customer Service                           7420
IT Support                                 5725
Billing and Payments                       4874
Returns and Exchanges                      2438
Service Outages and Maintenance            1912
Sales and Pre-Sales                        1490
Human Resources                             914
General Inquiry                             668
Pets & Animals/Pet Services                 386
News                                        383
IT & Technology/Security Operations         365
Autos & Vehicles/Sales                      364
Health/Medical Services                     362
Home & Garden/Home Improvement              361
Pets & Animals/Veterinary Care              356
Health/Mental Health                        347
Business & Industrial/Manufacturing         346
Online Communities/Forums                   343
Shopping/E-commerce                         341
Food & Drink/Groceries                      332
Travel & Transportation/Land Travel         331
Jobs & Education/Online Courses             329
Finance/Investments                         327
Law & Government/Government Services        326
Hobbies & Leisure/Collectibles              325
Online Communities/Social Networks          322
Books & Literature/Non-Fiction              320
Science/Environmental Science               318
Hobbies & Leisure/Crafts                    316
Finance/Personal Finance                    312
Science/Research                            310
IT & Technology/Network Infrastructure      302
Games                                       301
Travel & Transportation/Air Travel          300
Beauty & Fitness/Cosmetics                  300
Arts & Entertainment/Music                  298
Food & Drink/Restaurants                    295
Law & Government/Legal Advice               294
Autos & Vehicles/Maintenance                293
IT & Technology/Hardware Support            293
Jobs & Education/Recruitment                290
Books & Literature/Fiction                  289
Beauty & Fitness/Fitness Training           289
Shopping/Retail Stores                      283
People & Society/Culture & Society          283
Arts & Entertainment/Movies                 262
IT & Technology/Software Development        262
Home & Garden/Landscaping                   256
Sports                                      236
Real Estate                                 230
Name: count, dtype: int64

Priorities:
priority
medium      23378
high        21925
low         12765
critical     1914
very_low     1783
Name: count, dtype: int64

Types:
type
Incident    19444
Request     13950
Problem     10196
Change       4997
Name: count, dtype: int64

In [41]:
print("Number of queues:", tickets_df["queue"].nunique())
print("Number of priorities:", tickets_df["priority"].nunique())
print("Number of types:", tickets_df["type"].nunique())

Number of queues: 52
Number of priorities: 5
Number of types: 4

In [42]:
print(tickets_df.isnull().sum())

subject      5299
body            2
answer      13189
type        13178
queue           0
priority        0
language        0
version     33178
tag_1       13178
tag_2       13237
tag_3       13409
tag_4       17775
tag_5       34129
tag_6       48540
tag_7       55797
tag_8       59293
dtype: int64

In [43]:
print("Duplicate subjects:", tickets_df["subject"].duplicated().sum())
print("Duplicate bodies:", tickets_df["body"].duplicated().sum())

Duplicate subjects: 15129
Duplicate bodies: 8400

In [44]:
print(
    tickets_df.groupby("version").size().sort_values(ascending=False).head(20)
)

version
400.0    18599
52.0      9119
51.0       869
dtype: int64

In [45]:
pd.set_option("display.max_colwidth", 300)

tickets_df[["subject", "body", "queue", "priority", "type", "answer"]].sample(
    10, random_state=42
)

,subject,body,queue,priority,type,answer
59903,Sicherheitsverstoß im Krankenhaus-System,"Es wurde ein Sicherheitsverstoß festgestellt, der die Sicherheit der Patientendaten gefährdet hat.",Technical Support,high,Incident,"Wir werden dringend Maßnahmen ergreifen, um die Situation zu kontrollieren, die Untersuchung der Verletzung durchzuführen und den Schutz der Patientendaten zu gewährleisten."
24200,Trouble with WhatsApp Desktop,"Experienced technical difficulties during a marketing campaign coordination call involving WhatsApp Desktop. The issue might have arisen from recent software updates. Tried reinstalling the application and rebooting the system, but the problem still persists. We would appreciate your assistance ...",Technical Support,medium,Incident,"Hello [Name],\n\nWe hope this email finds you well. We are writing to acknowledge the issue you encountered with WhatsApp Desktop during your marketing campaign coordination call. We sincerely apologize for any inconvenience this has caused.\n\nTo better assist you, we would like to gather more ..."
35048,Sporadische Scannerfehler am Point of Sale,"Sehr geehrtes Support-Team,\n\nich schreibe Ihnen, um ein wiederkehrendes Problem mit dem Barcode-Scanner an unserer Kasse zu melden. Der Scanner weist zeitweise Fehlfunktionen auf, was zu Preisungenauigkeiten während des Bezahlvorgangs führt. Dieses Problem ist besonders angesichts unserer aktu...",Shopping/Retail Stores,low,None,None
31808,Markt-Alarm-Verzögerungen in der Handelsplattform,"Hallo Support-Team,\n\nich schreibe Ihnen, um ein Problem zu melden, das ich mit der Fidelity Active Trader Pro Plattform habe. Ich habe zeitweise Verzögerungen beim Empfang von Markt-Alarmen festgestellt. SilverLine Finance hat darauf hingewiesen, dass dies ein bekanntes Problem mit einer mögli...",Finance/Investments,medium,None,None
29641,Probleme bei der Buchung von Proberäumen,"Hallo Support,\n\nwir haben derzeit einige Fehlermeldungen beim Versuch, Proberäume über das Online-System zu buchen. Für dringende Buchungen gibt es eine temporäre Lösung über die Theaterkasse. Wir gehen davon aus, dass dieses Problem innerhalb der nächsten 24 Stunden behoben sein wird.\n\nViel...",Sports,medium,None,None
15142,Integration with Discord for Enhanced Team Collaboration,Inquiring about the process of integrating Discord into our project management SaaS to improve team collaboration. Would appreciate guidance on the specific features that will be available and the benefits of using Discord for team collaboration. Please provide details on the steps required to i...,Customer Service,high,Request,"<name> appreciates your interest in integrating Discord into the project management SaaS to enhance team collaboration. To set up the integration, navigate to the integrations section within the SaaS and select Discord from the list of available integrations. You will then be prompted to authori..."
59042,Enhancements for Safeguarding Medical Data,"Customer Support, please address the implementation of security enhancements for protecting medical data across hospital systems and related software products. Given the importance of safeguarding sensitive medical information, we believe it is essential that appropriate measures are taken to pr...",IT Support,medium,Change,"We appreciate your concern regarding the protection of medical data and will provide you with information on the current security protocols and future enhancements, including encryption methods and access controls. We will provide your account number and please specify your preferred time for a ..."
29088,"Wichtig: EV-Buchungssystem derzeit nicht verfügbar, betrifft Benutzer","An das Support-Team,\n\nwir haben derzeit Schwierigkeiten mit dem Buchungssystem der mobilen App.",Pets & Animals/Pet Services,high,None,None
24499,Details zu Digitalen Strategieleistungen für Markengröße,"Könnten Sie mehr Details zu den digitalen Strategieleistungen für Markengröße geben? Wir sind an der Möglichkeit interessiert, mehr über die Leistungen unserer Firma zu erfahren, um unsere Onlinepräsenz zu erweitern und neue Kunden zu erreichen. Danke für Ihre Zeit und ich freue mich auf Ihre Rü...",Technical Support,high,Request,"Sehr geehrte [Name], vielen Dank für Ihr Interesse an unseren digitalen Strategieleistungen für Markengröße. Unsere Leistungen umfassen Webseitenentwicklung, Suchmaschinenoptimierung, Sozialmedienmanagement und Online-Marketingkampagnen, um Ihre Onlinepräsenz zu erweitern und neue Kunden zu erre..."
61309,Issue with System Downtime Affecting Data Analytics Investment Optimization,"Hello Customer Support, I am currently working on a report that highlights an unexpected system downtime which is impacting our data analytics investment optimization. The problem might be due to resource overload on Microsoft Azure. Despite my attempts to restart Docker containers and clear cac...",Customer Service,medium,Incident,We will investigate the Microsoft Azure resource overload issue and contact us at <tel_num> to discuss the resolution steps. Please provide your account number <acc_num> for reference.

In [46]:
# Look at exact duplicate subject + body combinations

ticket_text = (
    tickets_df["subject"].fillna("") + " " +
    tickets_df["body"].fillna("")
)

print("Exact duplicate subject+body:", ticket_text.duplicated().sum())

Exact duplicate subject+body: 8306

In [47]:
temp = tickets_df.copy()

temp["ticket_text"] = (
    temp["subject"].fillna("") + " " +
    temp["body"].fillna("")
)

duplicate_groups = (
    temp.groupby("ticket_text")
    .agg(
        count=("ticket_text", "size"),
        queues=("queue", "nunique"),
        priorities=("priority", "nunique")
    )
)

print("Duplicate groups with conflicting queues:")
print(
    duplicate_groups[
        (duplicate_groups["count"] > 1) &
        (duplicate_groups["queues"] > 1)
    ].head(20)
)

Duplicate groups with conflicting queues:
Empty DataFrame
Columns: [count, queues, priorities]
Index: []

In [48]:
print("Duplicate groups with conflicting priorities:")
print(
    duplicate_groups[
        (duplicate_groups["count"] > 1) &
        (duplicate_groups["priorities"] > 1)
    ].head(20)
)

Duplicate groups with conflicting priorities:
Empty DataFrame
Columns: [count, queues, priorities]
Index: []

In [49]:
en_df = tickets_df[
    tickets_df["language"] == "en"
].copy()

print(en_df.shape)

(28261, 16)

In [50]:
print("English queue distribution:")
print(en_df["queue"].value_counts())

English queue distribution:
queue
Technical Support                  8149
Product Support                    5305
Customer Service                   4269
IT Support                         3333
Billing and Payments               2897
Returns and Exchanges              1402
Service Outages and Maintenance    1106
Sales and Pre-Sales                 843
Human Resources                     553
General Inquiry                     404
Name: count, dtype: int64

In [51]:
print("English priority distribution:")
print(en_df["priority"].value_counts())

English priority distribution:
priority
medium    11570
high      10917
low        5774
Name: count, dtype: int64

In [52]:
print(
    en_df.groupby("queue")["priority"]
    .value_counts()
    .head(30)
)

queue                            priority
Billing and Payments             medium      1436
                                 high         846
                                 low          615
Customer Service                 medium      2077
                                 low         1403
                                 high         789
General Inquiry                  low          239
                                 medium        99
                                 high          66
Human Resources                  low          263
                                 medium       232
                                 high          58
IT Support                       high        1580
                                 medium      1424
                                 low          329
Product Support                  medium      2693
                                 high        1600
                                 low         1012
Returns and Exchanges            medium       570
                                 low          517
                                 high         315
Sales and Pre-Sales              medium       389
                                 low          304
                                 high         150
Service Outages and Maintenance  high         776
                                 medium       189
                                 low          141
Technical Support                high        4737
                                 medium      2461
                                 low          951
Name: count, dtype: int64

In [53]:
print(
    tickets_df["version"]
    .value_counts()
    .sort_index()
)

version
51.0       869
52.0      9119
400.0    18599
Name: count, dtype: int64

In [54]:
print(
    tickets_df.groupby(["version", "language"]).size()
)

version  language
51.0     de            318
         en            551
52.0     de           3773
         en           5346
400.0    de           8158
         en          10441
dtype: int64

In [55]:
print("Number of English queues:", en_df["queue"].nunique())

print("\nSmallest English queues:")
print(
    en_df["queue"]
    .value_counts()
    .sort_values()
    .head(20)
)

Number of English queues: 10

Smallest English queues:
queue
General Inquiry                     404
Human Resources                     553
Sales and Pre-Sales                 843
Service Outages and Maintenance    1106
Returns and Exchanges              1402
Billing and Payments               2897
IT Support                         3333
Customer Service                   4269
Product Support                    5305
Technical Support                  8149
Name: count, dtype: int64

In [56]:
en_df["ticket_text"] = (
    en_df["subject"].fillna("") + "\n" +
    en_df["body"].fillna("")
)

print("English rows:", len(en_df))
print("Unique English tickets:", en_df["ticket_text"].nunique())
print("Duplicate English rows:", en_df["ticket_text"].duplicated().sum())

English rows: 28261
Unique English tickets: 23748
Duplicate English rows: 4513

In [57]:
print("\nDuplicates by version:")
print(
    en_df.groupby("version")["ticket_text"]
    .apply(lambda x: x.duplicated().sum())
)

Duplicates by version:
version
51.0     0
52.0     0
400.0    0
Name: ticket_text, dtype: int64

In [58]:
clean_df = en_df.copy()

# Remove exact duplicate tickets
clean_df = clean_df.drop_duplicates(
    subset=["subject", "body"]
).copy()

print("Before:", len(en_df))
print("After:", len(clean_df))
print("Removed:", len(en_df) - len(clean_df))

Before: 28261
After: 23748
Removed: 4513

In [59]:
print("Queue distribution:")
print(clean_df["queue"].value_counts())

print("\nPriority distribution:")
print(clean_df["priority"].value_counts())

Queue distribution:
queue
Technical Support                  6858
Product Support                    4430
Customer Service                   3570
IT Support                         2833
Billing and Payments               2420
Returns and Exchanges              1173
Service Outages and Maintenance     937
Sales and Pre-Sales                 724
Human Resources                     461
General Inquiry                     342
Name: count, dtype: int64

Priority distribution:
priority
medium    9754
high      9149
low       4845
Name: count, dtype: int64

In [60]:
print(
    pd.crosstab(
        clean_df["queue"],
        clean_df["priority"]
    )
)

priority                         high   low  medium
queue
Billing and Payments              714   515    1191
Customer Service                  666  1169    1735
General Inquiry                    54   202      86
Human Resources                    49   220     192
IT Support                       1334   278    1221
Product Support                  1318   845    2267
Returns and Exchanges             252   446     475
Sales and Pre-Sales               126   258     340
Service Outages and Maintenance   661   116     160
Technical Support                3975   796    2087

In [61]:
print("Missing subjects:", clean_df["subject"].isna().sum())
print("Missing bodies:", clean_df["body"].isna().sum())

Missing subjects: 2827
Missing bodies: 1

In [62]:
clean_df[
    ["subject", "body", "queue", "priority"]
].sample(10, random_state=42)

,subject,body,queue,priority
28221,Detected Unauthorized Access to Medical Data System Due to Phishing Email,Initial security protocols were activated following an unauthorized access attempt via a phishing email.,Customer Service,medium
58261,Report on Invoicing Error,"Respected Customer Support, I am contacting you to report a problem with the invoices I recently received. I was overcharged for the same service twice, which might indicate a problem with the billing system. Despite reaching out to support and reviewing my invoices online, the issue remains unr...",Billing and Payments,medium
23984,Problem with Real-Time Data Presentation,"The digital marketing analytics tool, which was supposed to display live data after the recent system update, is not functioning as expected. I have tried refreshing and clearing the cache, but the issue still persists.",IT Support,medium
24843,Report on Data Security Incident Involving Medical Records,"There has been a data security incident affecting medical records due to a software vulnerability which might have exposed the records. Despite updating protocols and conducting scans, the issue still exists.",Technical Support,medium
6122,Underwhelming Results of Digital Campaigns Due to Cross-Platform Integration Challenges,"Customer Support, preparing a report on the digital campaigns managed by the marketing agency, which have underperformed potentially because of integration problems across various platforms. We tested platform synchronization and updated the software; however, the issues continue. Our team is wo...",Customer Service,low
46560,Issues Arising from Heavy System Load,"There have been multiple instances of software crashes happening at the same time. It is suspected that the system is overloaded, leading to these crashes. Efforts to resolve the issue, such as restarting devices and updating software, have been made but the problem still exists. I need your hel...",Technical Support,high
52174,Project Timeline Not Displaying,The project timeline view is not displaying because of a database connectivity problem.,Technical Support,medium
694,Immediate Attention Required: Network Disruption Impacting Several Devices,"Dear Customer Support Team,\n\nI am submitting a report regarding a significant network interruption currently disrupting several devices. The cause appears to be either hardware or network-related. Despite our efforts, we have been unable to pinpoint or resolve the fundamental issue.\n\nTo diag...",Service Outages and Maintenance,high
5894,Hospital Network Security Concerns,Customer support has documented an incident involving unauthorized access attempts aimed at the hospital's sensitive medical data storage systems. The healthcare provider has indicated that these attempts may be linked to vulnerabilities in outdated PHP 8.0 and unpatched Git 2.32 software. Initi...,Technical Support,low
41995,Technical Support,"Reporting intermittent performance issues on the SaaS platform while accessing project files. The issue might be related to insufficient RAM or network instability, especially with NAS wireless connections. Despite restarting networking equipment and optimizing storage settings, the problem pers...",Customer Service,low

In [63]:
missing_subject = clean_df[
    clean_df["subject"].isna()
]

print("Missing subject rows:", len(missing_subject))

missing_subject[
    ["subject", "body", "queue", "priority"]
].sample(10, random_state=42)

Missing subject rows: 2827

,subject,body,queue,priority
16938,None,"Customer Support, I am facing connectivity issues with my Streaming-Kamera and WLAN-Router. This could possibly be due to network configuration errors. I have already rebooted the devices and checked the network settings, but the problem still persists. I am unable to establish a stable connecti...",Technical Support,high
8602,None,"Customer Support, I am reaching out to inquire about integrating a scalable SaaS project management platform with WordPress and BigCommerce. Could you provide comprehensive documentation on the process? I want to understand the steps involved and any potential challenges that might occur. Specif...",Product Support,medium
28487,None,May I request more information on the data analytics services that optimize investments? Your prompt assistance on this matter is greatly appreciated.,Customer Service,medium
5441,None,"Customer support, experiencing difficulties in retrieving pricing information. Recent updates to the website might be the cause. I have attempted clearing the cache and used various browsers, but the issue persists. Kindly help in resolving this problem.",Sales and Pre-Sales,low
20182,None,"Customer Support, requesting enhancements to integration features across affected products to better streamline project management workflows and make it easier for teams to collaborate and track progress. Currently, the lack of seamless integration is causing inefficiencies and delays in project...",Product Support,high
4750,None,"expressing curiosity about integrating RapidMiner into the current data analytics infrastructure. currently utilize a variety of tools and platforms to manage and analyze data, and are keen on exploring how RapidMiner can enhance these capabilities. Would greatly appreciate any guidance on the b...",Technical Support,high
26143,None,"Customer Support, we are reporting an incident related to a decrease in client engagement metrics over the past month. It is possible that recent algorithm changes on social media platforms could be the cause. Despite efforts to improve content quality and increase ad spending, there have been n...",Customer Service,low
4641,None,"Customer Support, I am reaching out to inquire about best practices for securing medical data within healthcare environments using Cassandra 4.0. Could you please provide guidance on this topic? I would appreciate any information you can share. Thank you for your time and assistance. I look forw...",Technical Support,high
6461,None,"Experiencing a report problem with digital tools integration that is affecting campaign execution. The issue seems to be linked to incompatible or outdated software versions. Attempts to fix the problem included updating Node.js, reinstalling Joomla, and troubleshooting OBS Studio configurations...",Customer Service,high
18569,None,"Dear Customer Support, I would like to draw your attention to a pressing matter concerning a security breach in the systems of our healthcare provider. Sensitive medical data has been compromised, and I am extremely concerned about the potential consequences. Initial investigation indicates that...",Customer Service,medium

In [64]:
print(
    "Missing subject + missing body:",
    missing_subject["body"].isna().sum()
)

Missing subject + missing body: 0

In [65]:
missing_subject["body"].str.len().describe()

count    2827.000000
mean      427.784577
std       181.104944
min         4.000000
25%       301.000000
50%       482.000000
75%       555.000000
max      1702.000000
Name: body, dtype: float64

In [66]:
print("Queues:")
print(missing_subject["queue"].value_counts())

print("\nPriorities:")
print(missing_subject["priority"].value_counts())

Queues:
queue
Technical Support                  821
Product Support                    509
Customer Service                   394
IT Support                         368
Billing and Payments               267
Returns and Exchanges              145
Sales and Pre-Sales                118
Service Outages and Maintenance     90
Human Resources                     64
General Inquiry                     51
Name: count, dtype: int64

Priorities:
priority
high      1131
medium    1119
low        577
Name: count, dtype: int64

In [67]:
# Make a clean copy
final_df = clean_df.copy()

# Remove the one ticket with no body
final_df = final_df.dropna(subset=["body"]).copy()

# Keep missing subjects for now
# We will handle them during training-data preparation

print("Final clean dataset:", final_df.shape)
print("Missing subjects:", final_df["subject"].isna().sum())
print("Missing bodies:", final_df["body"].isna().sum())

Final clean dataset: (23747, 17)
Missing subjects: 2827
Missing bodies: 0

In [68]:
final_df = final_df[
    ["subject", "body", "queue", "priority", "language", "version"]
].copy()

In [69]:
import os

processed_dir = "/content/drive/MyDrive/SupportOpsAI/data/processed"

os.makedirs(processed_dir, exist_ok=True)

clean_path = os.path.join(
    processed_dir,
    "english_clean.csv"
)

final_df.to_csv(clean_path, index=False)

print(f"Saved to: {clean_path}")

Saved to: /content/drive/MyDrive/SupportOpsAI/data/processed/english_clean.csv

In [70]:
check_df = pd.read_csv(clean_path)

print(check_df.shape)
print(check_df.head())

(23747, 6)
                                                  subject  \
0                                      Account Disruption
1      Query About Smart Home System Integration Features
2                       Inquiry Regarding Invoice Details
3  Question About Marketing Agency Software Compatibility
4                                           Feature Query

                                                                                                                                                                                                                                                                                                          body  \
0  Dear Customer Support Team,\n\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to account settings, leading to substantial inconvenience. I have attempted to log in multiple times u...
1  Dear Customer Support Team,\n\nI hope this message reaches you well. I am reaching out to request detailed information about the capabilities of your smart home integration products listed on your website. As a potential customer aiming to develop a seamlessly interconnected home environment, it...
2  Dear Customer Support Team,\n\nI hope this message finds you well. I am reaching out to request clarification about the billing and payment procedures linked to my account. Recently, I observed some inconsistencies in the charges applied and would like to ensure I fully understand the billing cy...
3  Dear Support Team,\n\nI hope this message reaches you well. I am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies. Our company is considering adopting these solutions to streamline our current marketing processes and wants to confirm that...
4  Dear Customer Support,\n\nI hope this message reaches you in good health. I am eager to learn more about the features of one of your products. Would you be able to share comprehensive details about its functionalities, specifications, and any distinctive characteristics it may possess? Additiona...

                   queue priority language  version
0      Technical Support     high       en     51.0
1  Returns and Exchanges   medium       en     51.0
2   Billing and Payments      low       en     51.0
3    Sales and Pre-Sales   medium       en     51.0
4      Technical Support     high       en     51.0

In [1]:
!ls

sample_data

In [1]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
import pandas as pd

clean_path = "/content/drive/MyDrive/SupportOpsAI/data/processed/english_clean.csv"

final_df = pd.read_csv(clean_path)

print(final_df.shape)
print(final_df.columns)

(23747, 6)
Index(['subject', 'body', 'queue', 'priority', 'language', 'version'], dtype='object')

In [4]:
print(final_df["queue"].value_counts())
print()
print(final_df["priority"].value_counts())

queue
Technical Support                  6858
Product Support                    4429
Customer Service                   3570
IT Support                         2833
Billing and Payments               2420
Returns and Exchanges              1173
Service Outages and Maintenance     937
Sales and Pre-Sales                 724
Human Resources                     461
General Inquiry                     342
Name: count, dtype: int64

priority
medium    9753
high      9149
low       4845
Name: count, dtype: int64

In [8]:
!ls

drive  sample_data

In [3]:
from sklearn.model_selection import train_test_split

final_df["stratify_label"] = (
    final_df["queue"] + " | " + final_df["priority"]
)

train_df, temp_df = train_test_split(
    final_df,
    test_size=0.20,
    random_state=42,
    stratify=final_df["stratify_label"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["stratify_label"]
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 18997
Validation: 2375
Test: 2375

In [4]:
train_df = train_df.drop(columns=["stratify_label"])
val_df = val_df.drop(columns=["stratify_label"])
test_df = test_df.drop(columns=["stratify_label"])

In [11]:
train_df.to_csv(
    "/content/drive/MyDrive/SupportOpsAI/data/processed/train.csv",
    index=False
)

val_df.to_csv(
    "/content/drive/MyDrive/SupportOpsAI/data/processed/validation.csv",
    index=False
)

test_df.to_csv(
    "/content/drive/MyDrive/SupportOpsAI/data/processed/test.csv",
    index=False
)

print("Saved train/validation/test splits.")

Saved train/validation/test splits.

In [5]:
def format_ticket(row):
    subject = row["subject"] if row["subject"] else ""
    body = row["body"]

    return {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a customer support ticket classifier. "
                    "Classify the ticket and return only valid JSON."
                )
            },
            {
                "role": "user",
                "content": (
                    f"Subject: {subject}\n\n"
                    f"Body: {body}"
                )
            },
            {
                "role": "assistant",
                "content": (
                    f'{{"queue": "{row["queue"]}", '
                    f'"priority": "{row["priority"]}"}}'
                )
            }
        ]
    }

In [6]:
train_formatted = train_df.apply(format_ticket, axis=1).tolist()
val_formatted = val_df.apply(format_ticket, axis=1).tolist()
test_formatted = test_df.apply(format_ticket, axis=1).tolist()

print("Train examples:", len(train_formatted))
print("Validation examples:", len(val_formatted))
print("Test examples:", len(test_formatted))

Train examples: 18997
Validation examples: 2375
Test examples: 2375

In [14]:
train_formatted[0]

{'messages': [{'role': 'system',
   'content': 'You are a customer support ticket classifier. Classify the ticket and return only valid JSON.'},
  {'role': 'user',
   'content': 'Subject: Inquiry on Jenkins Integration with Our SaaS Platform\n\nBody: Hello, I am contacting you to request information about integrating Jenkins with your project management software. Could you share any documentation or guides you have for this process? I am particularly interested in understanding the benefits and challenges of this integration. I look forward to your response and to discussing this further.'},
  {'role': 'assistant',
   'content': '{"queue": "Product Support", "priority": "medium"}'}]}

In [7]:
from datasets import Dataset

train_dataset = Dataset.from_list(train_formatted)
val_dataset = Dataset.from_list(val_formatted)
test_dataset = Dataset.from_list(test_formatted)

print(train_dataset)
print(val_dataset)
print(test_dataset)

Dataset({
    features: ['messages'],
    num_rows: 18997
})
Dataset({
    features: ['messages'],
    num_rows: 2375
})
Dataset({
    features: ['messages'],
    num_rows: 2375
})

In [8]:
from transformers import AutoTokenizer

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Tokenizer loaded")

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Tokenizer loaded

In [17]:
print(tokenizer.chat_template)

{%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0]['role'] == 'system' %}
        {{- messages[0]['content'] }}
    {%- else %}
        {{- 'You are Qwen, created by Alibaba Cloud. You are a helpful assistant.' }}
    {%- endif %}
    {{- "\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0]['role'] == 'system' %}
        {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
    {%- else %}
        {{- '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) or (message.role == "assistant" and not message.tool_calls) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {{- '<|im_start|>' + message.role }}
        {%- if message.content %}
            {{- '\n' + message.content }}
        {%- endif %}
        {%- for tool_call in message.tool_calls %}
            {%- if tool_call.function is defined %}
                {%- set tool_call = tool_call.function %}
            {%- endif %}
            {{- '\n<tool_call>\n{"name": "' }}
            {{- tool_call.name }}
            {{- '", "arguments": ' }}
            {{- tool_call.arguments | tojson }}
            {{- '}\n</tool_call>' }}
        {%- endfor %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if (loop.index0 == 0) or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
{%- endif %}

In [9]:
text = tokenizer.apply_chat_template(
    train_dataset[0]["messages"],
    tokenize=False,
    add_generation_prompt=False
)

print(text)

<|im_start|>system
You are a customer support ticket classifier. Classify the ticket and return only valid JSON.<|im_end|>
<|im_start|>user
Subject: Inquiry on Jenkins Integration with Our SaaS Platform

Body: Hello, I am contacting you to request information about integrating Jenkins with your project management software. Could you share any documentation or guides you have for this process? I am particularly interested in understanding the benefits and challenges of this integration. I look forward to your response and to discussing this further.<|im_end|>
<|im_start|>assistant
{"queue": "Product Support", "priority": "medium"}<|im_end|>

In [10]:
tokens = tokenizer(
    text,
    return_tensors="pt"
)

print(tokens["input_ids"].shape)

torch.Size([1, 117])

In [20]:
print(tokens["input_ids"][0][:30])

tensor([151644,   8948,    198,   2610,    525,    264,   6002,   1824,  11727,
         33365,     13,   3228,   1437,    279,  11727,    323,    470,   1172,
          2697,   4718,     13, 151645,    198, 151644,    872,    198,  13019,
            25,  65702,    389])

In [11]:
print(tokenizer.convert_ids_to_tokens(tokens["input_ids"][0][:30]))

['<|im_start|>', 'system', 'Ċ', 'You', 'Ġare', 'Ġa', 'Ġcustomer', 'Ġsupport', 'Ġticket', 'Ġclassifier', '.', 'ĠClass', 'ify', 'Ġthe', 'Ġticket', 'Ġand', 'Ġreturn', 'Ġonly', 'Ġvalid', 'ĠJSON', '.', '<|im_end|>', 'Ċ', '<|im_start|>', 'user', 'Ċ', 'Subject', ':', 'ĠInquiry', 'Ġon']

In [12]:
def apply_chat_template(example):
    example["text"] = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )
    return example


train_dataset = train_dataset.map(apply_chat_template)
val_dataset = val_dataset.map(apply_chat_template)
test_dataset = test_dataset.map(apply_chat_template)

Map:   0%|          | 0/18997 [00:00<?, ? examples/s]

Map:   0%|          | 0/2375 [00:00<?, ? examples/s]

Map:   0%|          | 0/2375 [00:00<?, ? examples/s]

In [19]:
print(train_dataset.column_names)

['messages', 'text']

In [20]:
print(train_dataset[0]["text"])

<|im_start|>system
You are a customer support ticket classifier. Classify the ticket and return only valid JSON.<|im_end|>
<|im_start|>user
Subject: Inquiry on Jenkins Integration with Our SaaS Platform

Body: Hello, I am contacting you to request information about integrating Jenkins with your project management software. Could you share any documentation or guides you have for this process? I am particularly interested in understanding the benefits and challenges of this integration. I look forward to your response and to discussing this further.<|im_end|>
<|im_start|>assistant
{"queue": "Product Support", "priority": "medium"}<|im_end|>

In [23]:
token_lengths = [
    len(tokenizer(x["text"])["input_ids"])
    for x in train_dataset
]

print("Min:", min(token_lengths))
print("Max:", max(token_lengths))
print("Average:", sum(token_lengths) / len(token_lengths))

Min: 54
Max: 370
Average: 122.63178396588935

In [25]:
from transformers import AutoModelForCausalLM
import torch

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [1]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

CUDA available: True
GPU: Tesla T4

In [28]:
print(model.hf_device_map if hasattr(model, "hf_device_map") else "No device map")

No device map

In [2]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import os

project_path = "/content/drive/MyDrive/SupportOpsAI"

print(os.path.exists(project_path))
print(os.listdir(project_path))

True
['data']

In [11]:
import os

project_path = "/content/drive/MyDrive/SupportOpsAI"
processed_path = f"{project_path}/data/processed"

print("Project exists:", os.path.exists(project_path))
print("Processed data:")
print(os.listdir(processed_path))

Project exists: True
Processed data:
['train.csv', 'validation.csv', 'english_clean.csv', 'test.csv']

In [12]:
import pandas as pd

processed_path = "/content/drive/MyDrive/SupportOpsAI/data/processed"

train_df = pd.read_csv(f"{processed_path}/train.csv")
val_df = pd.read_csv(f"{processed_path}/validation.csv")
test_df = pd.read_csv(f"{processed_path}/test.csv")

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

Train: (18997, 6)
Validation: (2375, 6)
Test: (2375, 6)

In [13]:
from transformers import AutoTokenizer

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Tokenizer loaded")

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Tokenizer loaded

In [14]:
from datasets import Dataset

def format_ticket(row):
    subject = row["subject"] if pd.notna(row["subject"]) else ""
    body = row["body"]

    return {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a customer support ticket classifier. "
                    "Classify the ticket and return only valid JSON."
                )
            },
            {
                "role": "user",
                "content": (
                    f"Subject: {subject}\n\n"
                    f"Body: {body}"
                )
            },
            {
                "role": "assistant",
                "content": (
                    f'{{"queue": "{row["queue"]}", '
                    f'"priority": "{row["priority"]}"}}'
                )
            }
        ]
    }

train_formatted = train_df.apply(format_ticket, axis=1).tolist()
val_formatted = val_df.apply(format_ticket, axis=1).tolist()
test_formatted = test_df.apply(format_ticket, axis=1).tolist()

train_dataset = Dataset.from_list(train_formatted)
val_dataset = Dataset.from_list(val_formatted)
test_dataset = Dataset.from_list(test_formatted)

print(len(train_dataset), len(val_dataset), len(test_dataset))

18997 2375 2375

In [15]:
def apply_chat_template(example):
    example["text"] = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )
    return example

train_dataset = train_dataset.map(apply_chat_template)
val_dataset = val_dataset.map(apply_chat_template)
test_dataset = test_dataset.map(apply_chat_template)

Map:   0%|          | 0/18997 [00:00<?, ? examples/s]

Map:   0%|          | 0/2375 [00:00<?, ? examples/s]

Map:   0%|          | 0/2375 [00:00<?, ? examples/s]

In [16]:
print(train_dataset[0]["text"])

<|im_start|>system
You are a customer support ticket classifier. Classify the ticket and return only valid JSON.<|im_end|>
<|im_start|>user
Subject: Inquiry on Jenkins Integration with Our SaaS Platform

Body: Hello, I am contacting you to request information about integrating Jenkins with your project management software. Could you share any documentation or guides you have for this process? I am particularly interested in understanding the benefits and challenges of this integration. I look forward to your response and to discussing this further.<|im_end|>
<|im_start|>assistant
{"queue": "Product Support", "priority": "medium"}<|im_end|>

In [17]:
import torch
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

print(model.device)

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

cuda:0

In [18]:
messages = [
    {
        "role": "system",
        "content": (
            "You are a customer support ticket classifier. "
            "Classify the ticket and return only valid JSON."
        )
    },
    {
        "role": "user",
        "content": (
            "Subject: Wireless mouse stopped working\n\n"
            "Body: My wireless mouse suddenly stopped responding. "
            "I replaced the batteries but it still does not work."
        )
    }
]

prompt = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=30
    )

generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

response = tokenizer.decode(
    generated_tokens,
    skip_special_tokens=True
)

print(response)

{
  "classification": "hardware malfunction"
}

In [19]:
import torch

SYSTEM_PROMPT = """You are a customer support ticket classifier.

Choose exactly one queue from:
Technical Support
Product Support
Customer Service
IT Support
Billing and Payments
Returns and Exchanges
Service Outages and Maintenance
Sales and Pre-Sales
Human Resources
General Inquiry

Choose exactly one priority from:
low
medium
high

Return ONLY valid JSON in exactly this format:
{"queue": "<queue>", "priority": "<priority>"}
"""

def predict_ticket(subject, body):
    subject = subject if pd.notna(subject) else ""

    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": f"Subject: {subject}\n\nBody: {body}"
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=30,
            do_sample=False
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    return tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

In [22]:
import json
import re
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, f1_score
from tqdm.auto import tqdm

# Allowed labels
ALLOWED_QUEUES = {
    "Technical Support",
    "Product Support",
    "Customer Service",
    "IT Support",
    "Billing and Payments",
    "Returns and Exchanges",
    "Service Outages and Maintenance",
    "Sales and Pre-Sales",
    "Human Resources",
    "General Inquiry"
}

ALLOWED_PRIORITIES = {"low", "medium", "high"}

# Make sure tokenizer can pad
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "left"


def parse_prediction(response):
    """
    Extract JSON from model response and validate labels.
    """
    response = response.strip()

    # First try the entire response
    try:
        data = json.loads(response)
    except json.JSONDecodeError:
        # Try extracting a JSON object from surrounding text
        match = re.search(r'\{.*?\}', response, re.DOTALL)

        if not match:
            return None

        try:
            data = json.loads(match.group())
        except json.JSONDecodeError:
            return None

    if not isinstance(data, dict):
        return None

    queue = data.get("queue")
    priority = data.get("priority")

    if queue not in ALLOWED_QUEUES:
        return None

    if priority not in ALLOWED_PRIORITIES:
        return None

    return {
        "queue": queue,
        "priority": priority
    }


def predict_ticket(subject, body):
    subject = subject if pd.notna(subject) else ""

    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": f"Subject: {subject}\n\nBody: {body}"
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=30,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    return tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()


# Run baseline
baseline_results = []

for _, row in tqdm(
    test_df.iterrows(),
    total=len(test_df),
    desc="Running baseline"
):
    raw_output = predict_ticket(
        row["subject"],
        row["body"]
    )

    prediction = parse_prediction(raw_output)

    baseline_results.append({
        "subject": row["subject"],
        "body": row["body"],
        "true_queue": row["queue"],
        "true_priority": row["priority"],
        "raw_output": raw_output,
        "pred_queue": prediction["queue"] if prediction else None,
        "pred_priority": prediction["priority"] if prediction else None,
        "valid_json": prediction is not None
    })

baseline_df = pd.DataFrame(baseline_results)

print("\nBaseline evaluation complete!")
print("Tickets evaluated:", len(baseline_df))

Running baseline:   0%|          | 0/2375 [00:00<?, ?it/s]

Baseline evaluation complete!
Tickets evaluated: 2375

In [23]:
queue_accuracy = accuracy_score(
    baseline_df["true_queue"],
    baseline_df["pred_queue"]
)

queue_f1 = f1_score(
    baseline_df["true_queue"],
    baseline_df["pred_queue"],
    average="macro",
    zero_division=0
)

priority_accuracy = accuracy_score(
    baseline_df["true_priority"],
    baseline_df["pred_priority"]
)

priority_f1 = f1_score(
    baseline_df["true_priority"],
    baseline_df["pred_priority"],
    average="macro",
    zero_division=0
)

joint_accuracy = (
    (baseline_df["true_queue"] == baseline_df["pred_queue"]) &
    (baseline_df["true_priority"] == baseline_df["pred_priority"])
).mean()

json_validity = baseline_df["valid_json"].mean()


print("========== BASELINE RESULTS ==========")
print(f"Queue Accuracy:       {queue_accuracy:.4f}")
print(f"Queue Macro-F1:       {queue_f1:.4f}")
print(f"Priority Accuracy:    {priority_accuracy:.4f}")
print(f"Priority Macro-F1:    {priority_f1:.4f}")
print(f"Joint Accuracy:       {joint_accuracy:.4f}")
print(f"JSON Validity:        {json_validity:.4f}")

TypeError: '<' not supported between instances of 'NoneType' and 'str'

In [24]:
# Only evaluate classification metrics on valid predictions
valid_df = baseline_df[baseline_df["valid_json"]].copy()

print("Total tickets:", len(baseline_df))
print("Valid predictions:", len(valid_df))
print("Invalid predictions:", len(baseline_df) - len(valid_df))


# Classification metrics
queue_accuracy = accuracy_score(
    valid_df["true_queue"],
    valid_df["pred_queue"]
)

queue_f1 = f1_score(
    valid_df["true_queue"],
    valid_df["pred_queue"],
    average="macro",
    zero_division=0
)

priority_accuracy = accuracy_score(
    valid_df["true_priority"],
    valid_df["pred_priority"]
)

priority_f1 = f1_score(
    valid_df["true_priority"],
    valid_df["pred_priority"],
    average="macro",
    zero_division=0
)


# Joint accuracy
joint_accuracy = (
    (valid_df["true_queue"] == valid_df["pred_queue"]) &
    (valid_df["true_priority"] == valid_df["pred_priority"])
).mean()


# JSON validity across ALL tickets
json_validity = baseline_df["valid_json"].mean()


print("\n========== BASELINE RESULTS ==========")
print(f"Queue Accuracy:       {queue_accuracy:.4f}")
print(f"Queue Macro-F1:       {queue_f1:.4f}")
print(f"Priority Accuracy:    {priority_accuracy:.4f}")
print(f"Priority Macro-F1:    {priority_f1:.4f}")
print(f"Joint Accuracy:       {joint_accuracy:.4f}")
print(f"JSON Validity:        {json_validity:.4f}")

Total tickets: 2375
Valid predictions: 2277
Invalid predictions: 98

========== BASELINE RESULTS ==========
Queue Accuracy:       0.3303
Queue Macro-F1:       0.2040
Priority Accuracy:    0.3944
Priority Macro-F1:    0.2375
Joint Accuracy:       0.1590
JSON Validity:        0.9587

In [25]:
strict_joint_accuracy = (
    (baseline_df["true_queue"] == baseline_df["pred_queue"]) &
    (baseline_df["true_priority"] == baseline_df["pred_priority"])
).mean()

print(f"Strict Joint Accuracy: {strict_joint_accuracy:.4f}")

Strict Joint Accuracy: 0.1524

In [26]:
strict_queue_accuracy = (
    baseline_df["true_queue"] == baseline_df["pred_queue"]
).mean()

strict_priority_accuracy = (
    baseline_df["true_priority"] == baseline_df["pred_priority"]
).mean()

print(f"Strict Queue Accuracy:    {strict_queue_accuracy:.4f}")
print(f"Strict Priority Accuracy: {strict_priority_accuracy:.4f}")
print(f"Strict Joint Accuracy:    {strict_joint_accuracy:.4f}")

Strict Queue Accuracy:    0.3166
Strict Priority Accuracy: 0.3781
Strict Joint Accuracy:    0.1524

In [4]:
import torch
import transformers
import datasets
import peft
import trl
import bitsandbytes

print("Python:", __import__("sys").version)
print("PyTorch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("\nLibraries:")
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("peft:", peft.__version__)
print("trl:", trl.__version__)
print("bitsandbytes:", bitsandbytes.__version__)

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
PyTorch: 2.11.0+cu128
CUDA: 12.8
CUDA available: True
GPU: Tesla T4

Libraries:
transformers: 5.16.1
datasets: 4.8.5
peft: 0.20.0
trl: 1.13.0
bitsandbytes: 0.50.2

In [5]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [6]:
import os

PROJECT_DIR = "/content/drive/MyDrive/SupportOpsAI"

print(os.listdir(PROJECT_DIR))

['data']

In [7]:
import pandas as pd

processed_path = f"{PROJECT_DIR}/data/processed"

train_df = pd.read_csv(f"{processed_path}/train.csv")
val_df = pd.read_csv(f"{processed_path}/validation.csv")
test_df = pd.read_csv(f"{processed_path}/test.csv")

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

Train: (18997, 6)
Validation: (2375, 6)
Test: (2375, 6)

In [8]:
from transformers import AutoTokenizer

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"

print("Tokenizer loaded")
print("Pad token:", tokenizer.pad_token)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Tokenizer loaded
Pad token: <|endoftext|>

In [9]:
from datasets import Dataset

SYSTEM_PROMPT = """You are a customer support ticket classifier.

Choose exactly one queue from:
Technical Support
Product Support
Customer Service
IT Support
Billing and Payments
Returns and Exchanges
Service Outages and Maintenance
Sales and Pre-Sales
Human Resources
General Inquiry

Choose exactly one priority from:
low
medium
high

Return ONLY valid JSON in exactly this format:
{"queue": "<queue>", "priority": "<priority>"}
"""


def format_ticket(row):
    subject = row["subject"] if pd.notna(row["subject"]) else ""

    return {
        "messages": [
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": (
                    f"Subject: {subject}\n\n"
                    f"Body: {row['body']}"
                )
            },
            {
                "role": "assistant",
                "content": (
                    f'{{"queue": "{row["queue"]}", '
                    f'"priority": "{row["priority"]}"}}'
                )
            }
        ]
    }


train_dataset = Dataset.from_list(
    train_df.apply(format_ticket, axis=1).tolist()
)

val_dataset = Dataset.from_list(
    val_df.apply(format_ticket, axis=1).tolist()
)

test_dataset = Dataset.from_list(
    test_df.apply(format_ticket, axis=1).tolist()
)

print(train_dataset)
print(val_dataset)
print(test_dataset)

Dataset({
    features: ['messages'],
    num_rows: 18997
})
Dataset({
    features: ['messages'],
    num_rows: 2375
})
Dataset({
    features: ['messages'],
    num_rows: 2375
})

In [10]:
def apply_chat_template(example):
    example["text"] = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )
    return example


train_dataset = train_dataset.map(apply_chat_template)
val_dataset = val_dataset.map(apply_chat_template)
test_dataset = test_dataset.map(apply_chat_template)

Map:   0%|          | 0/18997 [00:00<?, ? examples/s]

Map:   0%|          | 0/2375 [00:00<?, ? examples/s]

Map:   0%|          | 0/2375 [00:00<?, ? examples/s]

In [11]:
print(train_dataset[0]["text"])

<|im_start|>system
You are a customer support ticket classifier.

Choose exactly one queue from:
Technical Support
Product Support
Customer Service
IT Support
Billing and Payments
Returns and Exchanges
Service Outages and Maintenance
Sales and Pre-Sales
Human Resources
General Inquiry

Choose exactly one priority from:
low
medium
high

Return ONLY valid JSON in exactly this format:
{"queue": "<queue>", "priority": "<priority>"}
<|im_end|>
<|im_start|>user
Subject: Inquiry on Jenkins Integration with Our SaaS Platform

Body: Hello, I am contacting you to request information about integrating Jenkins with your project management software. Could you share any documentation or guides you have for this process? I am particularly interested in understanding the benefits and challenges of this integration. I look forward to your response and to discussing this further.<|im_end|>
<|im_start|>assistant
{"queue": "Product Support", "priority": "medium"}<|im_end|>

In [12]:
import numpy as np

lengths = []

for example in train_dataset:
    tokens = tokenizer(
        example["text"],
        add_special_tokens=False
    )["input_ids"]

    lengths.append(len(tokens))

print("Min:", min(lengths))
print("Max:", max(lengths))
print("Average:", np.mean(lengths))

Min: 122
Max: 438
Average: 191.51250197399588

In [13]:
import torch

from transformers import (
    AutoModelForCausalLM,
    BitsAndBytesConfig
)


bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)


model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
)

print("QLoRA base model loaded")
print("Device:", model.device)

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

QLoRA base model loaded
Device: cuda:0

In [14]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=True
)

print("Model prepared for k-bit training")

Model prepared for k-bit training

In [15]:
from peft import LoraConfig, get_peft_model


lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",

    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ],
)


model = get_peft_model(
    model,
    lora_config
)

model.print_trainable_parameters()

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

In [16]:
print("Model type:", type(model))
print("Trainable parameters:")

model.print_trainable_parameters()

Model type: <class 'peft.peft_model.PeftModelForCausalLM'>
Trainable parameters:
trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

In [17]:
from trl import SFTTrainer, SFTConfig
import inspect

print(inspect.signature(SFTConfig))
print("\n" + "="*80 + "\n")
print(inspect.signature(SFTTrainer))

(output_dir: str | None = None, per_device_train_batch_size: int = 8, num_train_epochs: float = 3.0, max_steps: int = -1, learning_rate: float = 2e-05, lr_scheduler_type: transformers.trainer_utils.SchedulerType | str = 'linear', lr_scheduler_kwargs: dict | str | None = None, warmup_steps: float = 0, optim: transformers.training_args.OptimizerNames | str = 'adamw_torch_fused', optim_args: str | None = None, weight_decay: float = 0.0, adam_beta1: float = 0.9, adam_beta2: float = 0.999, adam_epsilon: float = 1e-08, optim_target_modules: None | str | list[str] = None, gradient_accumulation_steps: int = 1, average_tokens_across_devices: bool = True, max_grad_norm: float = 1.0, label_smoothing_factor: float = 0.0, bf16: bool | None = None, fp16: bool = False, bf16_full_eval: bool = False, fp16_full_eval: bool = False, tf32: bool | None = None, gradient_checkpointing: bool = True, gradient_checkpointing_kwargs: dict[str, typing.Any] | str | None = None, torch_compile: bool = False, torch_compile_backend: str | None = None, torch_compile_mode: str | None = None, use_liger_kernel: bool = False, liger_kernel_config: dict[str, bool] | None = None, use_cache: bool = False, neftune_noise_alpha: float | None = None, torch_empty_cache_steps: int | None = None, auto_find_batch_size: bool = False, logging_strategy: transformers.trainer_utils.IntervalStrategy | str = 'steps', logging_steps: float = 10, logging_first_step: bool = False, log_on_each_node: bool = True, logging_nan_inf_filter: bool = True, include_num_input_tokens_seen: str | bool = 'no', log_level: str = 'passive', log_level_replica: str = 'warning', disable_tqdm: bool | None = None, report_to: None | str | list[str] = 'none', run_name: str | None = None, project: str = 'huggingface', trackio_space_id: str | None = None, trackio_bucket_id: str | None = None, trackio_static_space_id: Union[str, NoneType, Literal[False]] = None, eval_strategy: transformers.trainer_utils.IntervalStrategy | str = 'no', eval_steps: float | None = None, eval_delay: float = 0, per_device_eval_batch_size: int = 8, prediction_loss_only: bool = False, eval_on_start: bool = False, eval_do_concat_batches: bool = True, eval_use_gather_object: bool = False, eval_accumulation_steps: int | None = None, include_for_metrics: list[str] = <factory>, batch_eval_metrics: bool = False, save_only_model: bool = False, save_strategy: transformers.trainer_utils.SaveStrategy | str = 'steps', save_steps: float = 500, save_on_each_node: bool = False, save_total_limit: int | None = None, enable_jit_checkpoint: bool = False, push_to_hub: bool = False, hub_token: str | None = None, hub_private_repo: bool | None = None, hub_model_id: str | None = None, hub_strategy: transformers.trainer_utils.HubStrategy | str = 'every_save', hub_always_push: bool = False, hub_revision: str | None = None, load_best_model_at_end: bool = False, metric_for_best_model: str | None = None, greater_is_better: bool | None = None, ignore_data_skip: bool = False, restore_callback_states_from_checkpoint: bool = False, full_determinism: bool = False, seed: int = 42, data_seed: int | None = None, use_cpu: bool = False, accelerator_config: dict | str | None = None, parallelism_config: accelerate.parallelism_config.ParallelismConfig | None = None, dataloader_drop_last: bool = False, dataloader_num_workers: int = 0, dataloader_pin_memory: bool = True, dataloader_persistent_workers: bool = False, dataloader_prefetch_factor: int | None = None, dataloader_multiprocessing_context: str | None = None, dataloader_in_order: bool = True, remove_unused_columns: bool = True, label_names: list[str] | None = None, train_sampling_strategy: str = 'random', length_column_name: str = 'length', ddp_find_unused_parameters: bool | None = None, ddp_bucket_cap_mb: int | None = None, ddp_broadcast_buffers: bool | None = None, ddp_static_graph: bool | None = None, ddp_backend: str | None = None, ddp_timeout: int = 1800, fsdp: str | None = None, fsdp_config: dict[str, typing.Any] | str | None = None, deepspeed: dict | str | None = None, debug: str | list[transformers.debug_utils.DebugOption] = '', skip_memory_metrics: bool = True, do_train: bool = False, do_eval: bool = False, do_predict: bool = False, resume_from_checkpoint: str | None = None, local_rank: int = -1, model_init_kwargs: dict[str, typing.Any] | str | None = None, trust_remote_code: bool = False, router_aux_loss_coef: float = 0.001, chat_template_path: str | None = None, dataset_text_field: str = 'text', dataset_kwargs: dict[str, typing.Any] | str | None = None, dataset_num_proc: int | None = None, eos_token: str | None = None, max_length: int | None = 1024, truncation_mode: str = 'keep_start', shuffle_dataset: bool = False, packing: bool = False, packing_strategy: str = 'bfd', padding_free: bool = False, pad_to_multiple_of: int | None = None, eval_packing: bool | None = None, completion_only_loss: bool | None = None, assistant_only_loss: bool = False, loss_type: str | None = None, activation_offloading: bool = False, pad_token: str | None = None) -> None

================================================================================

(model: 'str | PreTrainedModel | PeftModel', args: trl.trainer.sft_config.SFTConfig | transformers.training_args.TrainingArguments | None = None, data_collator: collections.abc.Callable[[list[typing.Any]], dict[str, typing.Any]] | None = None, train_dataset: datasets.arrow_dataset.Dataset | datasets.iterable_dataset.IterableDataset | None = None, eval_dataset: datasets.arrow_dataset.Dataset | datasets.iterable_dataset.IterableDataset | datasets.dataset_dict.DatasetDict | datasets.dataset_dict.IterableDatasetDict | dict[str, datasets.arrow_dataset.Dataset | datasets.iterable_dataset.IterableDataset] | None = None, processing_class: transformers.tokenization_utils_base.PreTrainedTokenizerBase | transformers.processing_utils.ProcessorMixin | None = None, compute_loss_func: collections.abc.Callable | None = None, compute_metrics: collections.abc.Callable[[transformers.trainer_utils.EvalPrediction], dict] | None = None, callbacks: list[transformers.trainer_callback.TrainerCallback] | None = None, optimizers: tuple[torch.optim.optimizer.Optimizer | None, torch.optim.lr_scheduler.LambdaLR | None] = (None, None), optimizer_cls_and_kwargs: tuple[type[torch.optim.optimizer.Optimizer], dict[str, typing.Any]] | None = None, preprocess_logits_for_metrics: collections.abc.Callable[[torch.Tensor, torch.Tensor], torch.Tensor] | None = None, quantization_config: 'BitsAndBytesConfig | None' = None, peft_config: 'PeftConfig | None' = None, formatting_func: collections.abc.Callable[[dict], str] | None = None)

In [18]:
print(train_dataset)
print(val_dataset)

print(train_dataset[0]["text"])

Dataset({
    features: ['messages', 'text'],
    num_rows: 18997
})
Dataset({
    features: ['messages', 'text'],
    num_rows: 2375
})
<|im_start|>system
You are a customer support ticket classifier.

Choose exactly one queue from:
Technical Support
Product Support
Customer Service
IT Support
Billing and Payments
Returns and Exchanges
Service Outages and Maintenance
Sales and Pre-Sales
Human Resources
General Inquiry

Choose exactly one priority from:
low
medium
high

Return ONLY valid JSON in exactly this format:
{"queue": "<queue>", "priority": "<priority>"}
<|im_end|>
<|im_start|>user
Subject: Inquiry on Jenkins Integration with Our SaaS Platform

Body: Hello, I am contacting you to request information about integrating Jenkins with your project management software. Could you share any documentation or guides you have for this process? I am particularly interested in understanding the benefits and challenges of this integration. I look forward to your response and to discussing this further.<|im_end|>
<|im_start|>assistant
{"queue": "Product Support", "priority": "medium"}<|im_end|>

In [41]:
import gc
import torch

del trainer
del model

gc.collect()
torch.cuda.empty_cache()

print(
    "GPU memory:",
    round(torch.cuda.memory_allocated() / 1e9, 2),
    "GB"
)

GPU memory: 13.93 GB

In [42]:
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    torch_dtype=torch.float16,
    device_map="auto",
)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [43]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=True
)

OutOfMemoryError: CUDA out of memory. Tried to allocate 892.00 MiB. GPU 0 has a total capacity of 14.56 GiB of which 225.81 MiB is free. Including non-PyTorch memory, this process has 14.34 GiB memory in use. Of the allocated memory 14.04 GiB is allocated by PyTorch, and 162.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://docs.pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf)

In [ ]:
import torch

print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

x = torch.randn(4096, 4096, device="cuda", dtype=torch.bfloat16)
y = x @ x

torch.cuda.synchronize()

print("GPU test completed")

CUDA: True
GPU: Tesla T4
GPU test completed

In [27]:
del x, y
torch.cuda.empty_cache()

In [28]:
print(next(model.parameters()).device)

cuda:0

In [33]:
import gc
import torch

# Clean up current model
del trainer
del model

gc.collect()
torch.cuda.empty_cache()

print("GPU memory cleared")

GPU memory cleared

In [34]:
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    torch_dtype=torch.float16,
    device_map="auto",
)

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [35]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=False
)

In [36]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
    ],
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

In [37]:
from trl import SFTConfig

training_args = SFTConfig(
    output_dir=output_dir,

    # Training
    num_train_epochs=3,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,

    # Learning rate
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_steps=180,

    # T4 -> FP16
    fp16=True,
    bf16=False,

    # Faster training
    gradient_checkpointing=False,
    use_cache=True,

    # Sequence length
    max_length=512,
    packing=False,

    # Train on completion/answer tokens
    completion_only_loss=True,

    # Validation
    eval_strategy="epoch",
    per_device_eval_batch_size=8,

    # Checkpoints
    save_strategy="epoch",
    save_total_limit=2,

    # Best checkpoint
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    # Logging
    logging_strategy="steps",
    logging_steps=50,
    report_to="none",

    seed=42,

    dataset_text_field="text",
)

In [38]:
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
)

trainer.model.print_trainable_parameters()

Tokenizing train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

In [39]:
train_loader = trainer.get_train_dataloader()
batch = next(iter(train_loader))

batch = {
    k: v.to(model.device)
    for k, v in batch.items()
    if hasattr(v, "to")
}

torch.cuda.empty_cache()
torch.cuda.synchronize()

import time

start = time.time()

outputs = model(**batch)

torch.cuda.synchronize()

forward_time = time.time() - start

start = time.time()

outputs.loss.backward()

torch.cuda.synchronize()

backward_time = time.time() - start

print("Batch shape:", batch["input_ids"].shape)
print("Forward:", round(forward_time, 2), "sec")
print("Backward:", round(backward_time, 2), "sec")
print("Total:", round(forward_time + backward_time, 2), "sec")
print("GPU memory:", round(torch.cuda.memory_allocated() / 1e9, 2), "GB")

Batch shape: torch.Size([8, 241])
Forward: 1.02 sec
Backward: 1.3 sec
Total: 2.32 sec
GPU memory: 5.37 GB

In [40]:
train_result = trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

OutOfMemoryError: CUDA out of memory. Tried to allocate 446.00 MiB. GPU 0 has a total capacity of 14.56 GiB of which 217.81 MiB is free. Including non-PyTorch memory, this process has 14.35 GiB memory in use. Of the allocated memory 14.03 GiB is allocated by PyTorch, and 179.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://docs.pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf)

In [48]:
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    torch_dtype=torch.float16,
    device_map="auto",
)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [49]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=True
)

In [50]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
    ],
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

In [51]:
from trl import SFTConfig

training_args = SFTConfig(
    output_dir=output_dir,

    num_train_epochs=3,

    # Safe for the T4
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,

    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_steps=180,

    # T4
    fp16=True,
    bf16=False,

    # Memory saving
    gradient_checkpointing=True,
    use_cache=False,

    max_length=512,
    packing=False,

    completion_only_loss=True,

    eval_strategy="epoch",
    per_device_eval_batch_size=4,

    save_strategy="epoch",
    save_total_limit=2,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    logging_strategy="steps",
    logging_steps=50,
    report_to="none",

    seed=42,

    dataset_text_field="text",
)

In [52]:
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
)

trainer.model.print_trainable_parameters()

Tokenizing train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

In [53]:
train_loader = trainer.get_train_dataloader()
batch = next(iter(train_loader))

batch = {
    k: v.to(model.device)
    for k, v in batch.items()
    if hasattr(v, "to")
}

torch.cuda.empty_cache()
torch.cuda.synchronize()

import time

start = time.time()

outputs = model(**batch)

torch.cuda.synchronize()

forward_time = time.time() - start

start = time.time()

outputs.loss.backward()

torch.cuda.synchronize()

backward_time = time.time() - start

print("Batch:", batch["input_ids"].shape)
print("Forward:", round(forward_time, 2), "sec")
print("Backward:", round(backward_time, 2), "sec")
print("Total:", round(forward_time + backward_time, 2), "sec")
print("GPU memory:", round(torch.cuda.memory_allocated() / 1e9, 2), "GB")

Batch: torch.Size([4, 241])
Forward: 0.53 sec
Backward: 0.76 sec
Total: 1.29 sec
GPU memory: 3.53 GB

In [54]:
training_args = SFTConfig(
    output_dir=output_dir,

    num_train_epochs=3,

    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,

    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_steps=180,

    fp16=True,
    bf16=False,

    gradient_checkpointing=True,
    use_cache=False,

    max_length=512,
    packing=False,

    completion_only_loss=True,

    eval_strategy="epoch",
    per_device_eval_batch_size=4,

    save_strategy="epoch",
    save_total_limit=2,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    logging_strategy="steps",
    logging_steps=50,
    report_to="none",

    seed=42,
    dataset_text_field="text",
)

In [55]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
)

Tokenizing train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

In [56]:
train_loader = trainer.get_train_dataloader()
batch = next(iter(train_loader))

batch = {
    k: v.to(model.device)
    for k, v in batch.items()
    if hasattr(v, "to")
}

torch.cuda.empty_cache()
torch.cuda.synchronize()

import time

start = time.time()

outputs = model(**batch)

torch.cuda.synchronize()
forward_time = time.time() - start

start = time.time()

outputs.loss.backward()

torch.cuda.synchronize()
backward_time = time.time() - start

print("Batch:", batch["input_ids"].shape)
print("Forward:", round(forward_time, 2), "sec")
print("Backward:", round(backward_time, 2), "sec")
print("Total:", round(forward_time + backward_time, 2), "sec")
print("GPU memory:", round(torch.cuda.memory_allocated() / 1e9, 2), "GB")

Batch: torch.Size([8, 241])
Forward: 0.87 sec
Backward: 1.32 sec
Total: 2.19 sec
GPU memory: 4.25 GB

In [57]:
train_result = trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

NotImplementedError: "_amp_foreach_non_finite_check_and_unscale_cuda" not implemented for 'BFloat16'

In [58]:
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name, param.dtype)
        break

base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight torch.bfloat16

In [60]:
for name, param in model.named_parameters():
    if param.requires_grad:
        param.data = param.data.float()

In [61]:
from collections import Counter

trainable_dtypes = Counter(
    str(param.dtype)
    for param in model.parameters()
    if param.requires_grad
)

print(trainable_dtypes)

Counter({'torch.float32': 224})

In [64]:
training_args = SFTConfig(
    output_dir=output_dir,
    num_train_epochs=3,

    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,

    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_steps=180,

    fp16=False,
    bf16=False,

    gradient_checkpointing=True,
    use_cache=False,

    max_length=512,
    packing=False,

    eval_strategy="epoch",
    per_device_eval_batch_size=4,

    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    logging_strategy="steps",
    logging_steps=50,
    report_to="none",

    seed=42,
    dataset_text_field="text",
)

In [65]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
)

Tokenizing train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Dropping fully masked examples from train dataset:   0%|          | 0/18997 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

Dropping fully masked examples from eval dataset:   0%|          | 0/2375 [00:00<?, ? examples/s]

In [ ]:
train_result = trainer.train()

In [ ]:
from google.colab import drive
drive.mount("/content/drive")